services:
  - type: web
    name: tgbost
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "6216116804"
      - key: MIN_WITHDRAW
        value: "20"
      - key: REFERRAL_REWARD
        value: "1.0"
      - key: CURRENCY
        value: "৳"
      - key: USDT_RATE
        value: "120"
      - key: MIN_WITHDRAW_USDT
        value: "1.0"
      - key: WEBHOOK_DOMAIN
        sync: false
